export const DB_CONSTANTS = {
  DEFAULT_MAX_POOL_SIZE: 10,
  DEFAULT_MIN_POOL_SIZE: 2,
  DEFAULT_SERVER_SELECTION_TIMEOUT_MS: 5000,
  DEFAULT_SOCKET_TIMEOUT_MS: 45000,
  DEFAULT_CONNECT_TIMEOUT_MS: 10000,
  DEFAULT_RETRY_ATTEMPTS: 5,
  DEFAULT_RETRY_BASE_DELAY_MS: 200,
  DEFAULT_RETRY_MAX_DELAY_MS: 5000,
  DEFAULT_HEARTBEAT_FREQUENCY_MS: 10000,
} as const;

export const MONGOOSE_CONNECTION_EVENTS = {
  DISCONNECTED: 'disconnected',
  RECONNECTED: 'reconnected',
  ERROR: 'error',
} as const;
