import {
   CallHandler,
   ExecutionContext,
   Injectable,
   NestInterceptor,
   InternalServerErrorException,
} from '@nestjs/common';

import { Reflector } from '@nestjs/core';
import { Observable, map } from 'rxjs';
import { ZodType } from 'zod';
import { RESPONSE_SCHEMA_KEY } from '../decorators/response-schema.decorator';

@Injectable()
export class ResponseValidationInterceptor implements NestInterceptor {
   constructor(private readonly reflector: Reflector) {}

   intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
      const schema = this.reflector.get<ZodType>(RESPONSE_SCHEMA_KEY, context.getHandler());

      // Endpoint doesn't declare a response schema.
      if (!schema) {
         return next.handle();
      }

      return next.handle().pipe(
         map((response) => {
            const result = schema.safeParse(response);

            if (!result.success) {
               // IMPORTANT:
               // Do not expose schema details to client.
               // This means your own backend produced an invalid
               // response.
               throw new InternalServerErrorException('Invalid response generated by server.');
            }

            return result.data;
         }),
      );
   }
}
